[package]
name = 'AptosinoSandbox'
version = '1.0.0'

[addresses]
aptosino = "bfb4153132b66aa462b33d2a74c52a1b7fe711758af32f5b66dbff725a10f630"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"