[package]
name = 'AptosinoSandbox'
version = '1.0.0'

[addresses]
aptosino = "b2104bc99e57db595ad246a46ff3d57adce17fb33058703ae770c302d0a88b63"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"